### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by AlexAkulov** [leominov/prometheus-actions#1]
Если бы был докер имидж было бы гораздо удобнее.

**Comment by kttyt** [comment]
Опиши как команды на хосте должны исполняться из docker образа

**Comment by leominov** [comment]
Опа, да, образ сделаем. @kttyt, да кейсы то любые могут быть :)

**Comment by AlexAkulov** [comment]
@kttyt я хочу иметь один имидж с prometheus-actions который будет ходить по ssh на нужные хосты и выполнять там комманды.

**Comment by leominov** [comment]
latest скоро появится здесь: https://hub.docker.com/r/leominov/prometheus-actions
Тегированный будут появляться по мере выхода. В образе, естественно, ничего кроме этого ПО нет.
